### ISSUE TITLE
Failed to send cookie

### ISSUE THREAD

**Issue by t3mm1k** [Exponefrv1/univk_audio#3]
I had installed univk_audio via GitHub.
Then I had modified auth_example.py and auth_with_example.py, assigning my vk.com creds to the following variables:
When I running auth_with_example.py or auth_example.py. I get the following error message:
```Traceback (most recent call last):
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\univk_audio\async_auth.py", line 225, in __send_get_cookies_request
    async with self._session.get(
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 508, in _request
    req = self._request_class(
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 283, in __init__
    url2 = url.with_query(params)
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\yarl\_url.py", line 1007, in with_query
    new_query = self._get_str_query(*args, **kwargs) or ""
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\yarl\_url.py", line 968, in _get_str_query
    query = "&".join(self._query_seq_pairs(quoter, query.items()))
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\yarl\_url.py", line 931, in _query_seq_pairs
    yield quoter(key) + "=" + quoter(cls._query_var(val))
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\yarl\_url.py", line 946, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\t3mm1\Desktop\projects\steGAYlos team\case3-neebu\vk.py", line 22, in <module>
    asyncio.run(get_auth_cookies_with_example())
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\t3mm1\Desktop\projects\steGAYlos team\case3-neebu\vk.py", line 18, in get_auth_cookies_with_example
    cookies = await auth.get_auth_cookies(path = "cookies.txt")
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\univk_audio\async_auth.py", line 266, in get_auth_cookies
    raise err
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\univk_audio\async_auth.py", line 259, in get_auth_cookies
    cookie_string = await self.__send_get_cookies_request()
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\site-packages\univk_audio\async_auth.py", line 233, in __send_get_cookies_request
    raise GetCookiesRequestError("Failed to send/process 'Get Cookies' request") from err
univk_audio.auth_exceptions.GetCookiesRequestError: Failed to send/process 'Get Cookies' request
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000162C2BE5040>
Traceback (most recent call last):
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000162C2BE5040>
Traceback (most recent call last):
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\t3mm1\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed```

**Comment by t3mm1k** [comment]
I try change hash parameter on string 72 in "request_data.py" file to value "5fd509994f872859e4", but the error also occurred
